setup_cfg:
  device: 'cuda'

data_cfg:
  data_root: './data'
  batch_size: 32

model_cfg:
  num_classes: 10

train_cfg:
  epoch: 10
  learning_rate: 0.0001
  print_period: 100
  
  save_root: './result/max_acc.pth'
  save_dir: './result'
